name: solducci
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  currency_text_input_formatter: ^2.2.9
  intl: ^0.20.0

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  gsheets: ^0.5.0
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.10.0
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dev/.env
